server:
  port: 8086
  servlet:
    context-path: /services/be/code-service
  address: 0.0.0.0

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: auth_user
    password: auth_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

openai:
  api:
    key: "sk-TU_API_KEY_DE_OPENAI"
    url: "https://api.openai.com/v1/chat/completions"
    model: "gpt-4-turbo-preview"

doc:
  api:
    path: /doc/api
    title: User API
    description: Documentation for the User API
    version: 1.0.0